// packages/vue-sdk/src/components/QuickActions.vue
<script setup lang="ts">
/**
 * QuickActions - Predefined prompt buttons
 *
 * Provides a consistent UI for common actions that send predefined prompts.
 * Solutions can customize the actions list and optionally provide custom rendering via slots.
 *
 * @example
 * ```vue
 * <QuickActions
 *   :actions="[
 *     { id: 'objectives', label: '学习目标', prompt: '帮我设计学习目标' },
 *     { id: 'content', label: '学习过程', prompt: '帮我设计学习过程' },
 *   ]"
 *   @select-action="sendMessage"
 * />
 * ```
 */

export interface QuickAction {
  id: string
  label: string
  prompt: string
  disabled?: boolean
}

const props = defineProps<{
  actions: QuickAction[]
}>()

const emit = defineEmits<{
  selectAction: [prompt: string]
}>()

defineSlots<{
  action?: (props: { action: QuickAction; onClick: () => void }) => unknown
}>()

function handleClick(action: QuickAction) {
  if (!action.disabled) {
    emit('selectAction', action.prompt)
  }
}
</script>

<template>
  <div v-if="actions.length > 0" class="flex flex-wrap gap-2">
    <template v-for="action in actions" :key="action.id">
      <!-- Custom slot rendering -->
      <div v-if="$slots.action">
        <slot name="action" :action="action" :on-click="() => handleClick(action)" />
      </div>

      <!-- Default button rendering -->
      <button
        v-else
        :disabled="action.disabled"
        :class="[
          'inline-flex items-center gap-2 px-3 py-1.5',
          'text-sm font-medium rounded-lg',
          'transition-all duration-200',
          action.disabled
            ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
            : 'bg-blue-50 text-blue-700 hover:bg-blue-100 hover:shadow-sm active:scale-95',
        ]"
        @click="handleClick(action)"
      >
        {{ action.label }}
      </button>
    </template>
  </div>
</template>

// solutions/business/problem-explainer/frontend/src/components/QuickActions/QuickActions.tsx
import {
  Play,
  ArrowRight,
  HelpCircle,
  RefreshCw,
  MessageCircle,
  Lightbulb,
  Presentation,
} from 'lucide-react';

interface QuickActionsProps {
  onAction: (action: string) => void;
  disabled?: boolean;
}

const actions = [
  { id: 'start', label: '开始讲解', icon: Play, primary: true },
  { id: 'next', label: '下一步', icon: ArrowRight },
  { id: 'detail', label: '更详细', icon: HelpCircle },
  { id: 'example', label: '举一反三', icon: RefreshCw },
  { id: 'why', label: '为什么', icon: MessageCircle },
  { id: 'alternative', label: '其他解法', icon: Lightbulb },
  { id: 'ppt', label: '生成PPT', icon: Presentation },
];

export default function QuickActions({ onAction, disabled }: QuickActionsProps) {
  return (
    <div className="p-4 border-t">
      <h3 className="text-xs font-medium text-gray-500 mb-2">快捷指令</h3>
      <div className="flex flex-wrap gap-2">
        {actions.map((action) => (
          <button
            key={action.id}
            onClick={() => onAction(action.id)}
            disabled={disabled}
            className={`
              inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm
              transition-colors duration-200
              ${
                action.primary
                  ? 'bg-blue-500 text-white hover:bg-blue-600'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }
              disabled:opacity-50 disabled:cursor-not-allowed
            `}
          >
            <action.icon className="w-3.5 h-3.5" />
            {action.label}
          </button>
        ))}
      </div>
    </div>
  );
}
